import mongoose from 'mongoose';

// Direct-message conversation between exactly two portal users.
// `participants` is always lowercased and sorted; `key` is the sorted pair
// joined with '|'. Uniqueness lives on `key` — a unique index on the
// `participants` ARRAY would be per-element (multikey), which wrongly forbids
// one user from having two conversations.
const chatConversationSchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true },
  participants: {
    type: [String],
    required: true,
    validate: (v) => Array.isArray(v) && v.length === 2
  },
  // email -> display name snapshot (refreshed on each message send)
  participantNames: { type: Map, of: String, default: {} },
  lastMessageAt: { type: Date, default: Date.now },
  lastMessageText: { type: String, default: '' },
  lastMessageSender: { type: String, default: '' },
  createdAt: { type: Date, default: Date.now }
});

chatConversationSchema.index({ participants: 1, lastMessageAt: -1 });

const chatMessageSchema = new mongoose.Schema({
  conversationId: { type: mongoose.Schema.Types.ObjectId, ref: 'ChatConversation', required: true },
  senderEmail: { type: String, required: true, lowercase: true, trim: true },
  senderName: { type: String, default: '' },
  text: { type: String, default: '' },
  // Optional onboarding-ticket reference (set when a tag in a ticket comment
  // generated this message) — powers the "Go to ticket" action in the widget.
  ticket: {
    jobId: { type: mongoose.Schema.Types.ObjectId, ref: 'OnboardingJob', default: null },
    jobNumber: { type: Number, default: null },
    clientName: { type: String, default: '' },
    clientNumber: { type: Number, default: null }
  },
  // Uploaded files (images render inline with a lightbox; others as file chips)
  attachments: [{
    url: { type: String, required: true },
    filename: { type: String, default: '' },
    contentType: { type: String, default: '' }
  }],
  // Denormalized quote snapshot — rendering a reply never needs a join, and
  // the quote survives even if the original is deleted later.
  replyTo: {
    messageId: { type: mongoose.Schema.Types.ObjectId, default: null },
    senderEmail: { type: String, default: '' },
    senderName: { type: String, default: '' },
    text: { type: String, default: '' },
    hasAttachment: { type: Boolean, default: false }
  },
  readBy: { type: [String], default: [] },
  // 'tag' = generated by a ticket-comment tag (subject to the unread-email
  // escalation sweep); 'system' = digests/escalations; 'user' = typed by hand.
  source: { type: String, enum: ['user', 'tag', 'system'], default: 'user' },
  // Escalation bookkeeping for source:'tag' messages. A non-null timestamp
  // means "handled" (sent, or skipped because it was read in time).
  escalation: {
    emailSentAt: { type: Date, default: null },
    adminNotifiedAt: { type: Date, default: null }
  },
  createdAt: { type: Date, default: Date.now }
});

chatMessageSchema.index({ conversationId: 1, createdAt: -1 });
chatMessageSchema.index({ conversationId: 1, senderEmail: 1, readBy: 1 });
// Escalation sweep: find unhandled tag messages quickly
chatMessageSchema.index({ source: 1, 'escalation.emailSentAt': 1, createdAt: 1 });
chatMessageSchema.index({ source: 1, 'escalation.adminNotifiedAt': 1, createdAt: 1 });

export const ChatConversationModel = mongoose.model('ChatConversation', chatConversationSchema);
export const ChatMessageModel = mongoose.model('ChatMessage', chatMessageSchema);
